ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto442
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto442/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto442/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
