ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto442
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto442/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto442/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
